FactoryBot.define do
  factory :category do
    sequence(:name) { |n| "Category #{n}" }
    description { 'A test category description.' }
    association :user
  end
end

# Comments:
#  factory :category: This line is defining a factory named :category, which is a blueprint for creating test instances of the Category model.
#  sequence(:name): A sequence is used to generate unique values for a particular attribute. Here, it generates a unique name for each category.
#  description: This line sets the description for each instance of Category generated by the factory to 'A test category description.'.
#  association :user: This line uses the association method to define a connection between this factory and another one. It means every instance of Category created by the factory will be associated with a User instance.